/*
 * generated by Xtext 2.25.0
 */
package fr.istic.idm.group10.jsondsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractJsonDslScopeProvider extends DelegatingScopeProvider {
}
