/*
 * generated by Xtext 2.25.0
 */
package fr.istic.idm.group10.jsondsl.ui.tests;

import com.google.inject.Injector;
import fr.istic.idm.group10.jsondsl.ui.internal.JsondslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class JsonDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return JsondslActivator.getInstance().getInjector("fr.istic.idm.group10.jsondsl.JsonDsl");
	}

}
