/*
 * generated by Xtext 2.25.0
 */
package fr.istic.idm.group10.jsondsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class JsonDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("fr/istic/idm/group10/jsondsl/parser/antlr/internal/InternalJsonDsl.tokens");
	}
}
