/*
 * generated by Xtext 2.25.0
 */
package fr.istic.idm.group10.jsondsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractJsonDslValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(fr.istic.idm.group10.jsondsl.myDsl.MyDslPackage.eINSTANCE);
		return result;
	}
}
