/*
 * generated by Xtext 2.25.0
 */
package fr.istic.idm.group10.jsondsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class JsonDslStandaloneSetup extends JsonDslStandaloneSetupGenerated {

	public static void doSetup() {
		new JsonDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
