/*
 * generated by Xtext 2.25.0
 */
package fr.istic.idm.group10.jsondsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class JsonDslUiModule extends AbstractJsonDslUiModule {

	public JsonDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
