/*
 * generated by Xtext 2.25.0
 */
package fr.istic.idm.group10.jsondsl.ide;


/**
 * Use this class to register ide components.
 */
public class JsonDslIdeModule extends AbstractJsonDslIdeModule {
}
