/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Insert</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Insert#getTargetNode <em>Target Node</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Insert#getNameObject <em>Name Object</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getInsert()
 * @model
 * @generated
 */
public interface Insert extends Commandes
{
  /**
   * Returns the value of the '<em><b>Target Node</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target Node</em>' attribute.
   * @see #setTargetNode(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getInsert_TargetNode()
   * @model
   * @generated
   */
  String getTargetNode();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Insert#getTargetNode <em>Target Node</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target Node</em>' attribute.
   * @see #getTargetNode()
   * @generated
   */
  void setTargetNode(String value);

  /**
   * Returns the value of the '<em><b>Name Object</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name Object</em>' attribute.
   * @see #setNameObject(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getInsert_NameObject()
   * @model
   * @generated
   */
  String getNameObject();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Insert#getNameObject <em>Name Object</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name Object</em>' attribute.
   * @see #getNameObject()
   * @generated
   */
  void setNameObject(String value);

} // Insert
