/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Projection</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Projection#getNodename <em>Nodename</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Projection#getKeyname <em>Keyname</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getProjection()
 * @model
 * @generated
 */
public interface Projection extends Commandes
{
  /**
   * Returns the value of the '<em><b>Nodename</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nodename</em>' attribute.
   * @see #setNodename(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getProjection_Nodename()
   * @model
   * @generated
   */
  String getNodename();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Projection#getNodename <em>Nodename</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nodename</em>' attribute.
   * @see #getNodename()
   * @generated
   */
  void setNodename(String value);

  /**
   * Returns the value of the '<em><b>Keyname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Keyname</em>' attribute.
   * @see #setKeyname(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getProjection_Keyname()
   * @model
   * @generated
   */
  String getKeyname();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Projection#getKeyname <em>Keyname</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Keyname</em>' attribute.
   * @see #getKeyname()
   * @generated
   */
  void setKeyname(String value);

} // Projection
