/**
 * generated by Xtext 2.25.0
 */
package fr.istic.idm.group10.jsondsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Commandes</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.istic.idm.group10.jsondsl.myDsl.MyDslPackage#getCommandes()
 * @model
 * @generated
 */
public interface Commandes extends MainGrammar
{
} // Commandes
