/**
 * generated by Xtext 2.25.0
 */
package fr.istic.idm.group10.jsondsl.myDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Insert</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.istic.idm.group10.jsondsl.myDsl.Insert#getJsonfile <em>Jsonfile</em>}</li>
 *   <li>{@link fr.istic.idm.group10.jsondsl.myDsl.Insert#getNode <em>Node</em>}</li>
 * </ul>
 *
 * @see fr.istic.idm.group10.jsondsl.myDsl.MyDslPackage#getInsert()
 * @model
 * @generated
 */
public interface Insert extends Commandes
{
  /**
   * Returns the value of the '<em><b>Jsonfile</b></em>' containment reference list.
   * The list contents are of type {@link fr.istic.idm.group10.jsondsl.myDsl.JSonFile}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Jsonfile</em>' containment reference list.
   * @see fr.istic.idm.group10.jsondsl.myDsl.MyDslPackage#getInsert_Jsonfile()
   * @model containment="true"
   * @generated
   */
  EList<JSonFile> getJsonfile();

  /**
   * Returns the value of the '<em><b>Node</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Node</em>' containment reference.
   * @see #setNode(JSonObject)
   * @see fr.istic.idm.group10.jsondsl.myDsl.MyDslPackage#getInsert_Node()
   * @model containment="true"
   * @generated
   */
  JSonObject getNode();

  /**
   * Sets the value of the '{@link fr.istic.idm.group10.jsondsl.myDsl.Insert#getNode <em>Node</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Node</em>' containment reference.
   * @see #getNode()
   * @generated
   */
  void setNode(JSonObject value);

} // Insert
