/**
 * generated by Xtext 2.25.0
 */
package fr.istic.idm.group10.jsondsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>JSon Null</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.istic.idm.group10.jsondsl.myDsl.MyDslPackage#getJSonNull()
 * @model
 * @generated
 */
public interface JSonNull extends JSonObject, JSonAttribut
{
} // JSonNull
