/**
 * generated by Xtext 2.25.0
 */
package fr.istic.idm.group10.jsondsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>JSon Object</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.istic.idm.group10.jsondsl.myDsl.MyDslPackage#getJSonObject()
 * @model
 * @generated
 */
public interface JSonObject extends EObject
{
} // JSonObject
