/**
 * generated by Xtext 2.25.0
 */
package fr.istic.idm.group10.jsondsl.myDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Mult</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.istic.idm.group10.jsondsl.myDsl.Mult#getName <em>Name</em>}</li>
 *   <li>{@link fr.istic.idm.group10.jsondsl.myDsl.Mult#getListInterger <em>List Interger</em>}</li>
 * </ul>
 *
 * @see fr.istic.idm.group10.jsondsl.myDsl.MyDslPackage#getMult()
 * @model
 * @generated
 */
public interface Mult extends JSonObject, JSonAttribut
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.istic.idm.group10.jsondsl.myDsl.MyDslPackage#getMult_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.istic.idm.group10.jsondsl.myDsl.Mult#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>List Interger</b></em>' containment reference list.
   * The list contents are of type {@link fr.istic.idm.group10.jsondsl.myDsl.JsonInteger}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>List Interger</em>' containment reference list.
   * @see fr.istic.idm.group10.jsondsl.myDsl.MyDslPackage#getMult_ListInterger()
   * @model containment="true"
   * @generated
   */
  EList<JsonInteger> getListInterger();

} // Mult
