/**
 * generated by Xtext 2.25.0
 */
package fr.istic.idm.group10.jsondsl.myDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Mult</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.istic.idm.group10.jsondsl.myDsl.Mult#getListInterger <em>List Interger</em>}</li>
 * </ul>
 *
 * @see fr.istic.idm.group10.jsondsl.myDsl.MyDslPackage#getMult()
 * @model
 * @generated
 */
public interface Mult extends JSonObject, JSonAttribut
{
  /**
   * Returns the value of the '<em><b>List Interger</b></em>' containment reference list.
   * The list contents are of type {@link fr.istic.idm.group10.jsondsl.myDsl.JsonInteger}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>List Interger</em>' containment reference list.
   * @see fr.istic.idm.group10.jsondsl.myDsl.MyDslPackage#getMult_ListInterger()
   * @model containment="true"
   * @generated
   */
  EList<JsonInteger> getListInterger();

} // Mult
