/**
 * generated by Xtext 2.25.0
 */
package fr.istic.idm.group10.jsondsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.istic.idm.group10.jsondsl.myDsl.MyDslPackage#getOperation()
 * @model
 * @generated
 */
public interface Operation extends JSonObject, JSonAttribut
{
} // Operation
