/**
 * generated by Xtext 2.25.0
 */
package fr.istic.idm.group10.jsondsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Subset</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.istic.idm.group10.jsondsl.myDsl.Subset#getName <em>Name</em>}</li>
 *   <li>{@link fr.istic.idm.group10.jsondsl.myDsl.Subset#getJsonfile <em>Jsonfile</em>}</li>
 *   <li>{@link fr.istic.idm.group10.jsondsl.myDsl.Subset#getListNodes <em>List Nodes</em>}</li>
 * </ul>
 *
 * @see fr.istic.idm.group10.jsondsl.myDsl.MyDslPackage#getSubset()
 * @model
 * @generated
 */
public interface Subset extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.istic.idm.group10.jsondsl.myDsl.MyDslPackage#getSubset_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.istic.idm.group10.jsondsl.myDsl.Subset#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Jsonfile</b></em>' reference list.
   * The list contents are of type {@link fr.istic.idm.group10.jsondsl.myDsl.JSonFile}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Jsonfile</em>' reference list.
   * @see fr.istic.idm.group10.jsondsl.myDsl.MyDslPackage#getSubset_Jsonfile()
   * @model
   * @generated
   */
  EList<JSonFile> getJsonfile();

  /**
   * Returns the value of the '<em><b>List Nodes</b></em>' reference list.
   * The list contents are of type {@link fr.istic.idm.group10.jsondsl.myDsl.JSonObject}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>List Nodes</em>' reference list.
   * @see fr.istic.idm.group10.jsondsl.myDsl.MyDslPackage#getSubset_ListNodes()
   * @model
   * @generated
   */
  EList<JSonObject> getListNodes();

} // Subset
