/**
 * generated by Xtext 2.25.0
 */
package fr.istic.idm.group10.jsondsl.myDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Subset</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.istic.idm.group10.jsondsl.myDsl.Subset#getJsonfile <em>Jsonfile</em>}</li>
 *   <li>{@link fr.istic.idm.group10.jsondsl.myDsl.Subset#getListNodes <em>List Nodes</em>}</li>
 * </ul>
 *
 * @see fr.istic.idm.group10.jsondsl.myDsl.MyDslPackage#getSubset()
 * @model
 * @generated
 */
public interface Subset extends Commandes
{
  /**
   * Returns the value of the '<em><b>Jsonfile</b></em>' containment reference list.
   * The list contents are of type {@link fr.istic.idm.group10.jsondsl.myDsl.JSonFile}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Jsonfile</em>' containment reference list.
   * @see fr.istic.idm.group10.jsondsl.myDsl.MyDslPackage#getSubset_Jsonfile()
   * @model containment="true"
   * @generated
   */
  EList<JSonFile> getJsonfile();

  /**
   * Returns the value of the '<em><b>List Nodes</b></em>' containment reference list.
   * The list contents are of type {@link fr.istic.idm.group10.jsondsl.myDsl.JSonObject}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>List Nodes</em>' containment reference list.
   * @see fr.istic.idm.group10.jsondsl.myDsl.MyDslPackage#getSubset_ListNodes()
   * @model containment="true"
   * @generated
   */
  EList<JSonObject> getListNodes();

} // Subset
